# number of pytorch threads to allocate, seed for RNGs
num_threads: 2
seed: null # null for no or command-line seed

# asset parameters
init_prices: [1, 1, 1]
mean_returns: [-0.00005, 0.00015, 0.0004] # annual -2%, 4%, 10%
stdev_returns: [0.0001, 0.0000, 0.0001]
init_weights: [0.34, 0.33, 0.33]
# mean_returns: [-0.0005, 0.0005] # annual 6%, 2%, -4%
# stdev_returns: [0.0000, 0.0000]
# init_weights: [0.5, 0.5]
init_principal: 1000


# agent parameters
buffer_maxlen: 100000
batchsize: 256
min_alpha: 0.01
max_alpha: 10
policy_lr: 0.005
v_lr: 0.005
init_mu_r: 1
init_mu_c: 1
mu_lr: 0.001
enable_cuda: False
grad_clip_radius: null # set to null for no clipping
policy_hidden_units: 256
v_hidden_units: 256


# experiment parameters
algorithm_name: 'AC'
env_name: 'Omega' # 'Sharpe' 'Omega' 'Sortino'
env_target_return: 0.000
num_episodes: 300
episode_len: 253 # trading days in a year
checkpoint_interval: 2
loading_checkpoint: False
log_dir: '../data/'
