# MDP
num_states: 10
num_actions: 10
seed: 1994

# algorithm
policy_lr: 0.001
v_lr: 0.001
init_mu_r: 1
init_mu_c: 1
mu_lr: 0.0001
mu_floor: 0.01
grad_clip_radius: null # null for no clipping

# experiment
algorithm: 'LinearAC'
env_name: 'MDP'
num_steps: 100000
print_interval: 1000
logging: True
log_dir: 'data'
