# MDP
num_states: 20
num_actions: 20
r: 'r4'
c: 'c6'
transition_seed: 1994 # null for random seed
training_seed: null # null for random seed

# algorithm
q_lr: 0.001
rho_lr: 0.00001
rho_init: 0
eps: 0.01

# experiment
algorithm: 'TabularQ'
env_name: 'MDP'
num_steps: 5000000
print_interval: 10000
logging: True
log_dir: 'data'
mc_testing: True
