# MDP
num_states: 5
num_actions: 5
r: 'r4'
c: 'c4'
transition_seed: 1994 # null for random seed
training_seed: null # null for random seed

# algorithm
q_lr: 0.01
rho_lr: 0.0005
rho_init: 0
eps: 0.1

# experiment
algorithm: 'TabularQ'
env_name: 'MDP'
num_steps: 1000000
print_interval: 10000
logging: False
log_dir: 'data'
mc_testing: False
