# Environment configs
envs_module_name: 'main.core.envs'
env_config:
  class: 'RandomMDPEnv'
  args: [5, 5, 'r1', 'c1']  # [num_states, num_actions, reward_fnc, cost_fnc]
  kwargs:
    transition_seed: 1066

# Agent configs
agents_module_name: 'main.core.agents'
agent_config:
  class: 'TabularQAgent'
  args: [0.01, 0.001] # [q_lr, rho_lr]
  kwargs: {}

# IOManager configs
iomanager_config:
  class: Null  # Will break if not specified at runtime
  args: ['test_data']  # Output directory
  kwargs:
    interval: 1000  # Print interval
    agent_name: Null  # specified at runtime
    filename: Null  # specified at runtime

# Trial configs
trial_config:
  width: 100
  n_steps: 10000
  logging: True
  plotting: False
  stdouting: True
