# Environment configs
envs_module_name: 'main.core.envs'
env_config:
  class: 'RandomMDPEnv'
  args: [5, 5, 'r1', 'c1']  # [num_states, num_actions, reward_fnc, cost_fnc]
  kwargs:
    transition_seed: 1066

# Agent configs
agents_module_name: 'main.core.agents'
agent_config:
  class: 'TabularQAgent'
  args: [0.01, 0.001] # [q_lr, rho_lr]
  kwargs: {}

# IOManager configs
output_dir: '/home/wessle/work/costaware/data/experiment_runner_example'

# Trial configs
trial_config:
  width: 100
  print_interval: 10000
  n_steps: 100000
  logging: True
  plotting: False
  stdouting: True
