# This is an example config file specifying a single trial.


# Environment configs
envs_module_name: 'costaware.core.envs'
env_config:
  class: 'RandomMDPEnv'
  args: [5, 5, 'r1', 'c1']  # [num_states, num_actions, reward_fnc, cost_fnc]
  kwargs:
    transition_seed: 1066

# Agent configs
agents_module_name: 'costaware.core.agents'
agent_config:
  class: 'TabularQAgent'
  args: [0.01, 0.001] # [q_lr, rho_lr]
  kwargs: {}

# IOManager configs
iomanager_config:
  class: Null  # Will break if not specified at runtime
  args: ['test_data']  # Output directory
  kwargs:
    print_interval: 1000
    log_interval: 100000
    agent_name: Null  # specified at runtime
    filename: 'ratios'  # specified at runtime

# Trial configs
trial_config:
  width: 100  # Width of window for computing moving averages
  n_steps: 100000
  n_episodes: 1
  log: True
  plot: False
  print: True
