# asset parameters
init_prices: [1, 1, 1]
# mean_returns: [0.00024, 0.00005, -0.00015] # annual 6%, 2%, -4%
# stdev_returns: [0.0001, 0.0000, 0.0001]
mean_returns: [-0.005, 0.000, 0.005] # annual 6%
stdev_returns: [0.000, 0.000, 0.000]
init_weights: [0.34, 0.33, 0.33]
init_principal: 1000


# agent parameters
buffer_maxlen: 100000
batchsize: 64
min_alpha: 0.01
max_alpha: 10
policy_lr: 0.005
v_lr: 0.01
init_mu_r: 0
init_mu_c: 0
mu_lr: 0.01
enable_cuda: True
grad_clip_radius: null # set to null for no clipping
policy_hidden_units: 64
v_hidden_units: 64


# experiment parameters
algorithm_name: 'AC'
env_name: 'Omega' # 'Sharpe' 'Omega' 'Sortino'
env_target_return: 0.000
num_episodes: 2000
episode_len: 253 # trading days in a year
checkpoint_interval: 100
loading_checkpoint: False
log_dir: '../data/'
