# asset parameters
init_prices: [1, 1, 1]
mean_returns: [0.0005, 0.0005, -0.0005]
stdev_returns: [0.0001, 0.0000, 0.0001]
init_weights: [0.34, 0.33, 0.33]
init_principal: 100

# agent parameters
buffer_maxlen: 100000
batchsize: 64
discretization_steps: 4
q_lr: 0.001
rho_lr: 0.001
eps: 0.3
enable_cuda: True
grad_clip_radius: null # set to null for no clipping
rho_clip_radius: null # set to null for no clipping
Q_hidden_units: 64


# experiment parameters
algorithm_name: 'Q'
env_name: 'Omega' # 'Sharpe' 'Omega' 'Sortino'
num_episodes: 50
episode_len: 365
checkpoint_interval: 10
loading_checkpoint: False
log_dir: '../data/'
